name: Mirror JSON from OpenAI to Gist

on:
  workflow_dispatch:       # Allows manual triggering
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Gist repo
        uses: actions/checkout@v3

      - name: Fetch JSON from OpenAI
        run: |
          curl -sL https://chat.openai.com/sandbox/animal_crafting_progress_hosted.json -o animal_crafting_progress.json

      - name: Validate and commit if changed
        run: |
          cat animal_crafting_progress.json | jq . > /dev/null || { echo "Invalid JSON. Aborting."; exit 1; }
          git config user.name "AutoSyncBot"
          git config user.email "bot@animalcrafting.local"
          git add animal_crafting_progress.json
          git diff --cached --quiet || git commit -m "Sync: OpenAI JSON auto-mirrored"
          git push
